//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public int articleId { get; set; }
        public string headline { get; set; }
        public string description { get; set; }
        public string imageURL { get; set; }
        public int authorId { get; set; }
        public int categoryId { get; set; }
        public string subheading { get; set; }
    
        public virtual journalist journalist { get; set; }
        public virtual category category { get; set; }
    }
}
